sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BVg0HfMs/dKCUdiGXD0uNXzzaB/UIAvUF9XlmotO78iqmGTjKpsUkVhJ4OAbY+XY/T+ZwxF8tf02YEjW4Cj6MsKamIA4k2Lk752+oyuhjLV42OZmMSRrFM/9UJFvxMwTCNDgZw9pedV6SrIMGmXsiz1T7oqTiFk5OOMuPXpqHMfjVSOiTdpz4BRHw6L7uvBSVpsDNl9lO6sDs3EmVP6NFbPZqUlT+YK6JQBnwLpQPLWT8r8Ult62WrFEmJ1LB5O2knPupjOwO+w6Rhd5eTAhMO8lIzhWbTWPIwEvScRigz2NGOcZofMOw9tpFWcWbkGqCk+Xy7kLjTt9nmrwgxCkiX59Q/YilNwS4kPROP7E/g1v9qKGKR61VtEuV8ZhL25hNMTzy3y4QY3+cbLQoMj9u65Oqw13Uz5xCaYifCSpSscPPm/11pFDgxvALOmR1z7Y2/OuoM2FcyYHkNTpqRr6ayVNYoUz9gcQanfHBJeXjdMo3pGyZOaeUtch2aBm5OmAMJw/oJGGH1BHeZ5ZyB5nJHFMBdEfwaHDYb0bdh1ODpj9Z5ECZW9GVe9RwcE5bxqPWmBit2AnXkLydt0LgkThIBDULM/4J02/BaYTSNp1TCV8VTemVpI4z11IOEhC9bZgnUxVAhNmz2hoCYxVoC0ZC9IbQRonK/j0OdpMUDa8VvY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Caught-in-the-Net_2451
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy